import substancesData from '../../../assets/data/substances.json';

/**
 * Reference values from ADR 2025, Table A.
 *
 * These guard the seed data itself, not the code: substances.json is regenerated by
 * scripts/parse-un-numbers.py from the BAM data package, and a parser change or a new
 * regulation revision must not silently alter a hazard class or a Kemler number.
 * UN 3423 is here because it moved from class 8 to 6.1 between ADR 2023 and 2025.
 */
interface ISubstanceRow {
  un_number: string;
  name_de: string;
  hazard_class: string;
  kemler_number: string | null;
  packing_group: string | null;
  tunnel_code: string | null;
}

const rows = substancesData as ISubstanceRow[];

const findVariant = (unNumber: string, kemler: string): ISubstanceRow | undefined =>
  rows.find((row) => row.un_number === unNumber && row.kemler_number === kemler);

describe('substances.json reference values', () => {
  it('holds UN 3423 as toxic, not corrosive (changed with ADR 2025)', () => {
    const solid = findVariant('3423', '668');

    expect(solid).toBeDefined();
    expect(solid?.hazard_class).toBe('6.1');
    expect(solid?.packing_group).toBe('I');
    expect(solid?.tunnel_code).toBe('C/E');
  });

  it('holds UN 1203 petrol with Kemler 33', () => {
    const petrol = findVariant('1203', '33');

    expect(petrol?.hazard_class).toBe('3');
    expect(petrol?.name_de).toContain('BENZIN');
  });

  it('holds UN 1017 chlorine with Kemler 265', () => {
    expect(findVariant('1017', '265')?.hazard_class).toBe('2');
  });

  it('holds the substances added with ADR 2025', () => {
    const added = ['3551', '3556', '3560'];

    for (const unNumber of added) {
      expect(rows.some((row) => row.un_number === unNumber)).toBe(true);
    }
  });

  it('pads every UN number to four digits', () => {
    expect(rows.every((row) => /^\d{4}$/.test(row.un_number))).toBe(true);
  });

  it('assigns a hazard class to every entry', () => {
    expect(rows.every((row) => row.hazard_class.length > 0)).toBe(true);
  });
});
